// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/project/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/project/:id" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./project/[id]/page.jsx": {
    id: "project/[id]/page";
    page: "/project/:id";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "project/[id]/page": typeof import("./src/app/./project/[id]/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};